CREATE TABLE 
  music_album(
    ID INT GENERATED ALWAYS AS IDENTITY,
    LABEL_ID INT,
    AUTHOR_ID INT,
    GENRE_ID INT,
    PUBLISH_DATE DATE NOT NULL,
    ARCHIVED BOOLEAN NOT NULL,
    name VARCHAR(100),
    ON_SPOTIFY BOOLEAN,
    FOREIGN KEY (LABEL_ID) REFERENCES LABEL(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
    FOREIGN KEY(GENRE_ID) REFERENCES GENRE(ID)
);

CREATE TABLE genre(
    ID  INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(100),
    PRIMARY KEY(ID)
  );